### PR TITLE
Remove travis.yml, add circle.yml & modify origami.json to add Circle in place of Travis.

### PR DESCRIPTION
**Pull request by j-mes**
- Check for correct support link
- Change from Travis to Circle CI
- Remove travis.yml
- Add circle.yml
- Passed OBT verify check
- Passed OBT server check

### CODE REVIEW

**Comment by j-mes** [comment]
It would not let me run OBT server when I was going through the housekeeping steps. Some steps were deferred because they were already done previously.

**Comment by j-mes** [comment]
The shield link will look like the build's failing (due to being on a different branch now) but it'll pass when it's merged with the master branch.

**Comment by onishiweb** [comment]
Looks good. Feel free to merge.

I've not noticed the shield link changed in a lot of the other repos, does this mean it's something you're going to have to go back through?

**Comment by onishiweb** [comment]
Looks good :+1:

**Pull request merged**
